### ISSUE TITLE
sheet name or sheetid?

### ISSUE THREAD

**Issue by Zulus88** [miktim/AM_FILL#1]
Доброго дня miktim!
Не могу понять почему при обращении 
am_fill.in_field('some data', 'Помещение!A3', 'i');
получаю no_data_found

worbook имеет вид:
<sheets><sheet name="Основные сведения" sheetId="1" r:id="rId1"/><sheet name="Помещение" sheetId="4" r:id="rId2"/>

**Comment by miktim** [comment]
Доброе утро, Zulus.
Попробуйте заменить ссылку 'Лист!Ячейка' именованной областью ЛАТИНСКИМИ буквами.
Подобное наблюдал, но причину не нашел.
Учту и в выходные проверю.

**Comment by Zulus88** [comment]
Победил, дело не в кириллице
Дело  в том, что  sheet id = 2 не всегда означает sheet2.xml, связка нах-ся в файле _rels/workbook.xml.rels
в процедуре read_names_xlsx  закомментировал
    --t_ind := dbms_xslprocessor.valueof( dbms_xmldom.item( t_nl, i ), '@sheetId', 'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"' );

и поставил 
t_ind := i+1;

далее идет корректное считывание
    t_nd1 := blob2node(as_zip.get_file( p_xlsx, 'xl/worksheets/sheet'||t_ind||'.xml' ) );

метод "в лоб", но в пакете as_read_xlsx есть обработка привязки sheet id к файлу sheet?.xml, 
ключевая переменная(массив) -  t_sheet_ids

**Comment by miktim** [comment]
Вставил заплатку. AM_FILL_60523.sql. Если не затруднит, проверьте на вашем xlsx.

**Comment by Zulus88** [comment]
Проверил, неудача, все тот же no data found
бэктрейс указывает на строку:
r := context.merges(p_loc.sht_nr).first();
мне кажется нужно ввести 4-ый параметр, sheet_id,  в процедуру in_field

"неправильные" xlsx можно взять здесь:
http://dom.gosuslugi.ru/filestore/publicDownloadServlet?context=contentmanagement&uid=f442eb77-7d63-4c39-a169-5e1e2e51d6a0

**Comment by Zulus88** [comment]
нашел причину - не во всех листах есть merges (объединение ячеек), поэтому добавил в  align_loc строчку:
exception  when NO_DATA_FOUND then  return p_loc;
и заработало (:

**Comment by miktim** [comment]
Спасибо. Исправил.

**Comment by miktim** [comment]
ДД!
Исправил исправленное:
- в read_names_xlsx разыменование через r:Id
- merges: заменил exception на проверку exists;
- поправил вычисление нового rId;
- процедура in_sheet: лист дублируется с атрибутом state="visible".

Закрываем тему?

**Comment by Zulus88** [comment]
Да, конечно закрываем, спасибо. Был в отпуске
